--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iSrDxv/ScoreboardLib
build-by-default: false
branches:
- stable
projects:
  ScoreboardLib:
    path: ""
    model: virion
    type: library
...
